# Generated by Django 4.2.27 on 2026-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lion',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.CharField(choices=[('Backend', 'Backend'), ('SpringBoot', 'SpringBoot'), ('Frontend', 'Frontend')], max_length=20),
        ),
    ]
