# Generated by Django 4.2.27 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions', '0002_alter_lion_name_alter_lion_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.CharField(choices=[('Django', 'Django'), ('SpringBoot', 'SpringBoot'), ('Frontend', 'Frontend')], max_length=20),
        ),
    ]
