# Generated by Django 4.2.27 on 2026-03-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.CharField(choices=[('Django', 'Django'), ('SpringBoot', 'SpringBoot'), ('Frontend', 'Frontend')], max_length=30),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('lions', models.ManyToManyField(blank=True, related_name='tags', to='lions.lion')),
            ],
        ),
        migrations.CreateModel(
            name='LionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('bio', models.TextField(blank=True, verbose_name='자기소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='lions.lion')),
            ],
        ),
    ]
